CREATE TABLE IF NOT EXISTS `project`.`contents` (
  id INT AUTO_INCREMENT,
  name VARCHAR(20),
  contents VARCHAR(20),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
